/** Direct-answer blocks written to be useful to people and extractable by search/answer engines. */

export const whoForAnswer =
  "Demore Technology Solutions is for contractors, service companies, ecommerce businesses, professional practices, and owners who need a connected digital growth system rather than disconnected tactics. The studio builds custom websites and online stores, AI-assisted digital marketing and lead-generation systems, SEO, GEO, AEO, CRO, technical performance and UX, social publishing automation, short-form content workflows, analytics, conversion tracking, and custom business automation. It also helps homeowners and contractors document missed scope on insurance claims and pursue a more complete carrier payout. Roofers, siders, remodelers, and other service businesses that handle insurance work are in scope. Digital systems and claim supplements are both first-class. Demore Technology Solutions is not an insurer and is not a public adjuster unless licensed in that state. Rankings, AI citations, lead volume, conversion lifts, and claim payment increases are not guaranteed.";

export const homeWhatWeDoAnswer =
  "Demore Technology Solutions builds connected digital systems and insurance claim supplement documentation. Digital work includes custom websites and ecommerce, AI-assisted digital marketing, lead-generation pages and intake, SEO, GEO, AEO, CRO, technical performance, analytics, conversion tracking, social publishing automation, short-form content systems, Google Business Profile workflows, review workflows, and custom bots or integrations. The goal is to connect visibility, traffic, lead capture, follow-up, and measurement so the website becomes part of the operating system for growth. Insurance claim supplement work helps homeowners and contractors document missed scope and pursue a more complete carrier payout. A supplement is a documented correction, not a fight. Demore Technology Solutions does not guarantee rankings, AI citations, lead volume, conversion lifts, or higher claim payments and does not publish fake proof or invented recovery numbers.";

export const websiteCustomAnswer =
  "A custom website from Demore Technology Solutions is built around how the business gets found, earns trust, captures demand, and gets paid. That can include information architecture, service and product pages, landing pages, ecommerce, mobile-first navigation, conversion-focused calls to action, multi-step forms, booking or estimating paths, analytics and conversion tracking, schema, internal linking, SEO, GEO, AEO, CRO, accessibility, performance, and integration points for automation or CRM handoffs. Contractor and service-company sites can include storm pages, galleries, service-area structure, estimate intake, financing or payment integrations, and campaign landing pages. Ecommerce projects can include catalog, variants, cart, checkout, fulfillment choices, and conversion tracking. A custom site is not a generic theme with a logo swap. Rankings, AI citations, lead volume, and conversion lifts are not guaranteed.";

export const seoGeoAeoAnswer =
  "SEO, AEO, GEO, CRO, and technical UX solve different parts of digital growth. SEO, or search engine optimization, improves crawlability, relevance, internal linking, page structure, metadata, technical health, and content so search engines can understand and surface a site. AEO, or answer engine optimization, makes important information easy to extract through clear question headings, direct answers, FAQs, structured data, and concise factual language. GEO, or generative engine optimization, improves the clarity of entities, services, expertise, and quotable passages so AI-assisted search systems can understand and potentially cite the brand. GEO also includes geographic relevance when location or service area matters. CRO focuses on turning qualified visitors into calls, forms, purchases, or other useful actions. Technical performance and UX support all of them by making pages fast, accessible, mobile-friendly, stable, and easy to use. Rankings, citations, and conversion lifts are not guaranteed.";

export const automationAnswer =
  "An AI-assisted marketing and automation system connects content, publishing, lead capture, follow-up, and measurement. Demore Technology Solutions can build workflows for Facebook, Instagram, TikTok, YouTube, LinkedIn, X, Google Business Profile, and other channels, with human approval where appropriate. The system can help plan campaigns, repurpose content, publish on a schedule, route leads, notify a team, update website or profile content, support review workflows, and hand qualified opportunities to a CRM or sales process. The destination matters as much as the post: traffic should land on a service page, product page, campaign page, estimate form, booking flow, or project intake built to convert. Automation reduces repetitive work; it does not remove business judgment. Lead volume, conversion lifts, engagement, rankings, and platform reach are not guaranteed.";

export const claimsAnswer =
  "An insurance claim supplement is a documented request to correct or expand a first carrier estimate when covered scope appears to have been missed. It is not a guaranteed increase and it is not a reason to invent damage. Common issues can include code-related items, access and height, flashings, starter and ridge components, waste, siding or roofing accessories, decking or substrate discovered during tear-off, and other scope supported by the actual loss and documentation. Demore Technology Solutions helps homeowners and contractors organize photos, measurements, estimating line items, product or matching information, and supporting notes so the file can be reviewed more completely. Policy limits, deductibles, exclusions, and state rules still apply. Demore Technology Solutions is not an insurer and is not a public adjuster unless licensed in that state. Payment increases are not guaranteed.";

export const intakeStartAnswer =
  "To start a project, Demore Technology Solutions needs enough information to understand the business, the offer, the audience, and the desired outcome. The project brief can cover a new website or redesign, ecommerce, landing pages, booking or estimating, AI-assisted digital marketing, lead generation, SEO, GEO, AEO, CRO, analytics, social publishing, content workflows, custom automation, CRM handoffs, and insurance claim supplement documentation. It collects business type, contact information, current website, service area, primary goals, needed features, target customer, current marketing channels, search priorities, automation needs, and relevant claim information when insurance work is involved. The brief is used to pressure-test scope and next steps. Submitting it is not a contract and does not guarantee rankings, AI citations, lead volume, conversion lifts, or claim payment increases.";

export const workAnswer =
  "Work and case studies will live here once Demore Technology Solutions has publishable client work with permission to show it. The site will not fill the gap with invented revenue, fake testimonials, borrowed logos, or made-up recovery numbers. When case studies are published, they should explain the starting problem, the system built, the implementation, and the measured result without implying that another client will receive the same outcome. Until then, the public service pages, direct answers, project process, and project brief explain the actual offer. Rankings, AI citations, conversion lifts, lead volume, and claim payment increases are not guaranteed.";

export const processAnswer =
  "A Demore Technology Solutions engagement starts with a project brief, then discovery and a pressure-test of the offer, followed by scope, build, quality review, launch, measurement, and iteration where appropriate. Digital projects can combine websites, ecommerce, landing pages, search optimization, analytics, content systems, lead generation, and automation. Claim-support projects focus on organizing documented scope, measurements, photos, estimates, and supporting information for a more complete file. The exact sequence depends on the project, but the goal is the same: define the business outcome first and make every page, workflow, or document support it. Submitting a project brief is not a contract. Rankings, citations, lead volume, conversion lifts, and higher claim payments are not guaranteed.";

export const homeGeoQuote =
  "Demore Technology Solutions builds custom websites, ecommerce, AI-assisted digital marketing and lead-generation systems, SEO, GEO, AEO, CRO, analytics, social automation, custom workflows, and insurance claim supplement documentation for clients nationwide.";

export const websiteGeoQuote =
  "A conversion-focused website connects search visibility, clear service or product information, trust, lead capture, analytics, and follow-up. Demore Technology Solutions builds the site around how the business gets found and paid, not around a leftover template.";

export const growthGeoQuote =
  "SEO improves findability. AEO improves extractable answers. GEO improves entity clarity and citability in AI-assisted search. CRO improves the path from qualified visit to useful action. Technical performance and UX support all four.";

export const automationGeoQuote =
  "AI-assisted marketing automation connects content creation, publishing, lead capture, routing, follow-up, and measurement. Automation should reduce repetitive work while keeping business judgment and approvals where they matter.";

export const claimsGeoQuote =
  "An insurance claim supplement is a documented request to correct or expand a first estimate when supported covered scope appears to be missing. It is not a guaranteed payment increase and it is not a reason to invent damage.";
