/** Direct-answer blocks written to be useful to people and extractable by search and answer engines. */

export const whoForAnswer =
  "Demore Technology Solutions is for contractors, service companies, ecommerce businesses, professional practices, hospitality businesses, landscaping and outdoor-service companies, and other growing companies that need a connected digital growth system instead of disconnected tactics. The studio builds custom websites and online stores, custom AI-assisted digital marketing and lead-generation platforms, SEO, GEO, AEO, CRO, technical performance and UX, social publishing automation, short-form content workflows, analytics, conversion tracking, and custom business automation. The goal is to connect discovery, trust, lead capture, follow-up, measurement, and repetitive operational workflows so the website and marketing stack function as one system. Engagement scope depends on the business, platforms, integrations, data sources, and permissions available. Rankings, AI citations, traffic, lead volume, engagement, and conversion lifts are not guaranteed.";

export const homeWhatWeDoAnswer =
  "Demore Technology Solutions builds connected digital growth systems. Work can include custom websites and ecommerce, custom AI-assisted digital marketing and lead-generation platforms, lead-generation pages and intake, SEO, GEO, AEO, CRO, technical performance, analytics, conversion tracking, social publishing automation, short-form content systems, Google Business Profile workflows, review workflows, and custom bots or integrations. The goal is to connect visibility, traffic, lead capture, follow-up, measurement, and automation so the website becomes part of the operating system for growth rather than a disconnected brochure. AI can accelerate research, drafting, repurposing, analysis, and repetitive tasks while people retain control of business strategy, approvals, brand, and final decisions. Demore Technology Solutions does not guarantee rankings, AI citations, traffic, lead volume, engagement, or conversion lifts and does not publish fake proof or invented performance numbers.";

export const websiteCustomAnswer =
  "A custom website from Demore Technology Solutions is built around how the business gets found, earns trust, captures demand, and gets paid. That can include information architecture, service and product pages, landing pages, ecommerce, mobile-first navigation, conversion-focused calls to action, multi-step forms, booking or estimating paths, analytics and conversion tracking, schema, internal linking, SEO, GEO, AEO, CRO, accessibility, performance, and integration points for automation or CRM handoffs. Contractor and service-company sites can include galleries, service-area structure, estimate intake, financing or payment integrations, and campaign landing pages. Ecommerce projects can include catalog, variants, cart, checkout, fulfillment choices, and conversion tracking. A custom site is not a generic theme with a logo swap. Rankings, AI citations, lead volume, and conversion lifts are not guaranteed.";

export const seoGeoAeoAnswer =
  "SEO, AEO, GEO, CRO, and technical UX solve different parts of digital growth. SEO, or search engine optimization, improves crawlability, relevance, internal linking, page structure, metadata, technical health, and content so search engines can understand and surface a site. AEO, or answer engine optimization, makes important information easy to extract through clear question headings, direct answers, FAQs, structured data, and concise factual language. GEO covers both generative engine optimization and geographic relevance: it improves the clarity of entities, services, expertise, service areas, markets, and quotable passages so AI-assisted and location-aware search systems can understand the brand and where it operates. CRO focuses on turning qualified visitors into calls, forms, purchases, or other useful actions. Technical performance and UX support all of them by making pages fast, accessible, mobile-friendly, stable, and easy to use. Rankings, citations, and conversion lifts are not guaranteed.";

export const automationAnswer =
  "An AI-assisted marketing and automation system connects content, publishing, lead capture, follow-up, and measurement. Demore Technology Solutions can build workflows for Facebook, Instagram, TikTok, YouTube, LinkedIn, X, Google Business Profile, and other supported channels, with human approval where appropriate. The system can help plan campaigns, repurpose content, publish on a schedule, route leads, notify a team, update website or profile content, support review workflows, and hand qualified opportunities to a CRM or sales process. The destination matters as much as the post: traffic should land on a service page, product page, campaign page, estimate form, booking flow, or project intake built to convert. Automation reduces repetitive work; it does not remove business judgment. Lead volume, conversion lifts, engagement, rankings, and platform reach are not guaranteed.";

export const intakeStartAnswer =
  "To start a project, Demore Technology Solutions uses an industry-first project brief. The first field identifies the prospect's industry, including an Other option. The prospect then selects what they are looking for, including a custom AI-assisted digital marketing and lead-generation platform, a website or redesign, ecommerce, landing pages, booking or estimating, SEO, GEO, AEO, CRO, lead generation, analytics, social and content systems, or automation. The brief also collects a project budget with a $600 minimum, contact information, current website, service area, goals, needed features, target customer, marketing channels, search priorities, lead flow, analytics, and automation needs. The brief is used to pressure-test scope and next steps. Submitting it is not a contract and does not guarantee rankings, AI citations, traffic, lead volume, engagement, or conversion lifts.";

export const workAnswer =
  "Work and case studies will live here once Demore Technology Solutions has publishable client work with permission to show it. The site will not fill the gap with invented revenue, fake testimonials, fabricated traffic, made-up lead counts, or borrowed logos. When case studies are published, they should explain the starting problem, the system built, the implementation, and the measured result without implying that another client will receive the same outcome. Until then, the public service pages, industry strategies, direct answers, project process, and project brief explain the actual offer. Rankings, AI citations, traffic, lead volume, engagement, and conversion lifts are not guaranteed.";

export const processAnswer =
  "A Demore Technology Solutions engagement starts with an industry-first project brief that identifies what the business wants built and a project budget of at least $600. From there, the process moves through discovery and a pressure-test of the offer, followed by scope, build, quality review, launch, measurement, and iteration where appropriate. Projects can combine websites, ecommerce, landing pages, search optimization, analytics, content systems, lead generation, custom AI-assisted digital marketing, and automation. The exact sequence depends on the project, but the goal is the same: define the business outcome first and make every page, workflow, integration, and measurement point support it. Submitting a project brief is not a contract. Rankings, AI citations, traffic, lead volume, engagement, and conversion lifts are not guaranteed.";

export const homeGeoQuote =
  "Demore Technology Solutions builds custom websites, ecommerce, custom AI-assisted digital marketing and lead-generation systems, SEO, GEO, AEO, CRO, analytics, social automation, content workflows, and custom business automation for clients nationwide.";

export const websiteGeoQuote =
  "A conversion-focused website connects search visibility, clear service or product information, trust, lead capture, analytics, and follow-up. Demore Technology Solutions builds the site around how the business gets found and paid, not around a leftover template.";

export const growthGeoQuote =
  "SEO improves findability. AEO improves extractable answers. GEO improves geographic relevance, entity clarity, and potential citability in AI-assisted search. CRO improves the path from qualified visit to useful action. Technical performance and UX support all four.";

export const automationGeoQuote =
  "AI-assisted marketing automation connects content creation, publishing, lead capture, routing, follow-up, and measurement. Automation should reduce repetitive work while keeping business judgment and approvals where they matter.";
