import {capabilities} from './control-capabilities.ts';
export const consoleOverview = 'A central control center brings site profiles, specialist tasks, reviewed proposals, shared spending limits, lead pipelines, assignment history and operational alerts into one workspace. Independent review checks proposed work. Configured low- and medium-risk workflows can run automatically; high-risk changes require a human decision. Permissions, verification and rollback remain part of implementation.';
export const offeringReadiness = 'Demore currently operates hosted specialist analysis with independent review, shared spending controls, lead capture, automatic first-assignment and owner alerts. Website editing, deployment, advertising, social publishing, phone services and customer follow-up require scoped connectors, setup and validation. A listed specialist is not proof that its external actions are connected for a customer.';
export const leadGenerationOffering = 'Automated lead generation can connect industry-specific landing pages, permitted prospect sources, inbound qualification, source attribution, deduplication, CRM routing, consent-aware follow-up, appointment handoff and conversion reporting. Review targeting, contact accuracy, consent and channel permissions before outreach. Start with a focused campaign and measure qualified inquiries and booked outcomes; lead volume, rankings and revenue are not guaranteed.';
export function tailoredAutomation(industry:string,journey:string,missing:string[]=[]):Array<[string,string]>{
 const key=industry.toLowerCase();
 const useCase=/pizza|restaurant|pub|hospitality|food/.test(key)?'Route catering and private-event inquiries; support menu questions, booking handoffs and repeat-visit campaigns with consent.':/store|ecommerce|retail|shop/.test(key)?'Guide product selection, capture product inquiries, connect checkout measurement and consent-based recovery or replenishment workflows.':/landscap|contract|roof|construction|home service/.test(key)?'Qualify service area, job type and timing; route estimate requests, organize follow-up and track estimate-to-booking outcomes.':/professional|legal|account|consult|health|medical/.test(key)?'Qualify service fit and consultation requests, route to the right professional and track booking; keep sensitive records out of public chat.':'Qualify inquiries by service fit, location and timing, then connect the next booking, purchase or sales handoff.';
 return [['Control center for '+industry,consoleOverview],['Automated lead generation for your customer journey',useCase+' Priority journey: '+journey+'. '+leadGenerationOffering],['Priorities from your current website',missing.length?'Validate these signals not detected in the public scan: '+missing.slice(0,5).join(', ')+'. Repair the relevant conversion path before increasing campaign volume.':'Validate existing conversion paths and attribution before adding automation. Public HTML cannot confirm private CRM, consent or follow-up configuration.'],['Measurement and staged rollout','Confirm the industry and primary conversion, connect the smallest useful workflow, test lead capture and ownership, then measure '+journey+'. Expand only after reliable tracking and handoff.'],['Scope and activation',offeringReadiness]];
}
export const specialistKnowledge = capabilities.map(b=>b.name+': '+b.purpose+'. Expected output: '+b.output).join('\n');
export function customerPdfText(text:string){return text.replace(/https?:\/\/(?:www\.)?demoreexteriorsolutions\.com[^\s)]*/gi,'[internal reference]').replace(/demoreexteriorsolutions\.com/gi,'[internal reference]').replace(/Demore Exterior(?: Solutions)?/gi,'reference implementation');}

export function customerPdfData<T>(value:T):T {
 if(typeof value === "string") return customerPdfText(value) as T;
 if(Array.isArray(value)) return value.map(item=>customerPdfData(item)) as T;
 if(value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,customerPdfData(item)])) as T;
 return value;
}
