export const capabilities = [
  {
    id: "web-ux",
    name: "Web UX Specialist",
    purpose: "Review mobile usability and accessibility",
    output: "Usability findings",
  },
  {
    id: "performance",
    name: "Technical Performance Specialist",
    purpose: "Measure load performance, broken links and frontend errors",
    output: "Measured performance report",
  },
  {
    id: "lead-generation",
    name: "Lead Generation Specialist",
    purpose: "Qualify inbound demand and attribute lead sources",
    output: "Qualified lead proposal",
  },
  {
    id: "chief",
    name: "Orchestrator",
    purpose: "Classify requests, build bounded task plans and route to specialists",
    output: "Job plan with evidence, risks and dependencies",
  },
  {
    id: "reputation",
    name: "Reputation Specialist",
    purpose: "Monitor reviews and propose truthful responses",
    output: "Review findings and response drafts",
  },
  {
    id: "analytics",
    name: "Analytics Specialist",
    purpose: "Reconcile traffic, conversions and event coverage",
    output: "Metrics with time window and freshness",
  },
  {
    id: "security-infrastructure",
    name: "Security Infrastructure Reviewer",
    purpose: "Review access boundaries, infrastructure and secret handling",
    output: "Security findings without secret values",
  },
  {
    id: "qa-review",
    name: "Quality Assurance Agent",
    purpose: "Independently review specialist proposals",
    output: "Approve, reject or request changes with evidence",
  },
  {
    id: "geo-local",
    name: "GEO Specialist",
    purpose:
      "Audit service areas, local search and business information; include generative-search visibility",
    output: "Location coverage and citation findings",
  },
  {
    id: "aeo",
    name: "AEO Specialist",
    purpose: "Improve factual answers, FAQs and answer-engine visibility",
    output: "Evidence-backed answer recommendations",
  },
  {
    id: "social",
    name: "Social Media Specialist",
    purpose: "Draft channel-specific social content",
    output: "Content calendar and drafts",
  },
  {
    id: "schema",
    name: "Schema Specialist",
    purpose: "Validate structured data against visible business facts",
    output: "Schema findings and proposed patch",
  },
  {
    id: "email-sms",
    name: "Email / SMS Specialist",
    purpose: "Prepare consent-aware follow-up sequences and reminders",
    output: "Recipient-scoped message drafts",
  },
  {
    id: "cro",
    name: "CRO Specialist",
    purpose: "Inspect lead funnels, forms and calls to action",
    output: "Conversion hypotheses with measurable outcomes",
  },
  {
    id: "seo",
    name: "SEO Specialist",
    purpose: "Audit indexing, metadata and internal linking",
    output: "Prioritized SEO findings",
  },
  {
    id: "web-development",
    name: "Web Development Specialist",
    purpose: "Prepare isolated code changes and rollback instructions",
    output: "Reviewable patch and tests",
  },
  {
    id: "website-chatbot",
    name: "AI Chatbot Specialist",
    purpose: "Maintain visitor-assistant behavior and escalation",
    output: "Grounded response and handoff rules",
  },
  {
    id: "content",
    name: "Content Specialist",
    purpose: "Draft service pages, blogs and business content",
    output: "Draft with factual sources",
  },
  {
    id: "independent-review",
    name: "Independent Review",
    purpose: "Review evidence and the exact proposed change using a separate agent and provider",
    output: "Independent decision on the reviewed change",
  },
  {
    id: "competitor-intelligence",
    name: "Competitor Intelligence",
    purpose: "Track verified competitors, offers, pages, rankings and public reviews",
    output: "Dated competitor comparison",
  },
  {
    id: "crm-lead-routing",
    name: "CRM and Lead Routing",
    purpose: "Deduplicate leads, assign owners, track pipeline and source attribution",
    output: "Routing plan with duplicate prevention",
  },
  {
    id: "phone-agent-management",
    name: "Phone Agent Management",
    purpose: "Version phone knowledge, summarize calls and manage after-hours handoffs",
    output: "Versioned phone configuration and handoff checks",
  },
  {
    id: "qa-testing",
    name: "QA and Testing",
    purpose: "Run deterministic form, link, mobile, chatbot and API tests in preview",
    output: "Checks tied to the proposed release",
  },
  {
    id: "deployment",
    name: "Deployment Management",
    purpose: "Coordinate preview, verification, approved promotion and rollback",
    output: "Deployment manifest and verification evidence",
  },
  {
    id: "conversion-experiments",
    name: "Conversion Experiments",
    purpose: "Define allocation, primary metric, guardrails and stopping rules",
    output: "Experiment proposal and outcome analysis",
  },
  {
    id: "data-quality",
    name: "Data Quality",
    purpose: "Detect duplicate records, broken tracking and inconsistent business information",
    output: "Reconciliation report and repair proposal",
  },
  {
    id: "compliance-claims",
    name: "Compliance And Claims",
    purpose: "Check claims against approved company evidence and flag wording needing human review",
    output: "Claim-to-source report",
  },
  {
    id: "knowledge-sync",
    name: "Knowledge-Base Sync",
    purpose: "Track source versions and synchronize approved facts to website and phone agents",
    output: "Knowledge diff and provenance",
  },
  {
    id: "reporting",
    name: "Reporting",
    purpose: "Summarize site outcomes, spend, blocked work and decisions",
    output: "Weekly report with sources and freshness",
  },
  {
    id: "uptime-errors",
    name: "Uptime And Errors",
    purpose: "Collect synthetic health checks and deduplicated error incidents",
    output: "Incident with severity and recovery evidence",
  },
  {
    id: "cost-monitoring",
    name: "Cost Monitoring",
    purpose: "Reconcile token and platform costs, reservations and budgets",
    output: "Spend ledger and budget alerts",
  },
  {
    id: "social-autoposting",
    name: "Social Autoposting",
    purpose: "Coordinate approved scheduled content with the connected publishing service",
    output: "Delivery receipt and duplicate prevention",
  },
  {
    id: "storm-intelligence",
    name: "Storm Intelligence",
    purpose: "Monitor public local storm events without promising damage or coverage",
    output: "Source-backed storm advisory",
  },
] as const;
