/**
 *  Reference markets for later location pages.
 *  Not a public directory. Do not mass-produce city pages from this list.
 */
export type StateMarkets = {
  state: string;
  abbr: string;
  cities: readonly string[];
};

export const marketsByState: readonly StateMarkets[] = [
  {
    state: "Alabama",
    abbr: "AL",
    cities: ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa", "Hoover", "Dothan", "Auburn"],
  },
  {
    state: "Alaska",
    abbr: "AK",
    cities: ["Anchorage", "Fairbanks", "Juneau", "Wasilla", "Sitka"],
  },
  {
    state: "Arizona",
    abbr: "AZ",
    cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Gilbert", "Glendale", "Tempe", "Peoria", "Surprise", "Yuma", "Flagstaff"],
  },
  {
    state: "Arkansas",
    abbr: "AR",
    cities: ["Little Rock", "Fayetteville", "Fort Smith", "Springdale", "Jonesboro", "Rogers", "Conway", "North Little Rock"],
  },
  {
    state: "California",
    abbr: "CA",
    cities: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Fresno",
      "Sacramento",
      "Long Beach",
      "Oakland",
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "Irvine",
      "Chula Vista",
      "Fremont",
      "San Bernardino",
      "Modesto",
      "Fontana",
      "Oxnard",
      "Moreno Valley",
      "Huntington Beach",
      "Glendale",
      "Santa Clarita",
      "Garden Grove",
      "Oceanside",
      "Rancho Cucamonga",
      "Santa Rosa",
      "Ontario",
      "Elk Grove",
      "Corona",
      "Lancaster",
      "Palmdale",
      "Salinas",
      "Hayward",
      "Pomona",
      "Escondido",
      "Sunnyvale",
      "Pasadena",
      "Torrance",
      "Orange",
      "Fullerton",
      "Thousand Oaks",
      "Visalia",
      "Simi Valley",
      "Concord",
      "Roseville",
      "Santa Clara",
      "Vallejo",
      "Victorville",
      "Berkeley",
      "El Monte",
      "Downey",
      "Costa Mesa",
      "Inglewood",
      "Ventura",
      "West Covina",
      "Norwalk",
      "Carlsbad",
      "Fairfield",
      "Richmond",
      "Murrieta",
      "Burbank",
      "Antioch",
      "Daly City",
      "Temecula",
      "San Mateo",
    ],
  },
  {
    state: "Colorado",
    abbr: "CO",
    cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo", "Greeley", "Boulder", "Centennial", "Grand Junction"],
  },
  {
    state: "Connecticut",
    abbr: "CT",
    cities: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Danbury", "New Britain", "Bristol", "Meriden"],
  },
  {
    state: "Delaware",
    abbr: "DE",
    cities: ["Wilmington", "Dover", "Newark", "Middletown", "Bear"],
  },
  {
    state: "Florida",
    abbr: "FL",
    cities: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Hialeah",
      "Port St. Lucie",
      "Cape Coral",
      "Tallahassee",
      "Fort Lauderdale",
      "Pembroke Pines",
      "Hollywood",
      "Gainesville",
      "Miramar",
      "Coral Springs",
      "Clearwater",
      "Palm Bay",
      "West Palm Beach",
      "Lakeland",
      "Pompano Beach",
      "Miami Gardens",
      "Davie",
      "Sunrise",
      "Boca Raton",
      "Deltona",
      "Plantation",
      "Fort Myers",
      "Sarasota",
      "Pensacola",
      "Melbourne",
      "Daytona Beach",
      "Naples",
      "Kissimmee",
      "Ocala",
    ],
  },
  {
    state: "Georgia",
    abbr: "GA",
    cities: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs", "Roswell", "Johns Creek", "Warner Robins", "Albany", "Alpharetta", "Marietta", "Valdosta"],
  },
  {
    state: "Hawaii",
    abbr: "HI",
    cities: ["Honolulu", "East Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu", "Kaneohe", "Kahului"],
  },
  {
    state: "Idaho",
    abbr: "ID",
    cities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell", "Coeur d'Alene", "Twin Falls"],
  },
  {
    state: "Illinois",
    abbr: "IL",
    cities: ["Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Springfield", "Elgin", "Peoria", "Champaign", "Waukegan", "Cicero", "Bloomington", "Arlington Heights", "Evanston", "Schaumburg", "Bolingbrook", "Decatur"],
  },
  {
    state: "Indiana",
    abbr: "IN",
    cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers", "Bloomington", "Hammond", "Gary", "Lafayette", "Muncie", "Terre Haute", "Kokomo"],
  },
  {
    state: "Iowa",
    abbr: "IA",
    cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "West Des Moines", "Ankeny", "Waterloo", "Ames", "Council Bluffs", "Dubuque"],
  },
  {
    state: "Kansas",
    abbr: "KS",
    cities: ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence", "Shawnee", "Manhattan", "Lenexa", "Salina"],
  },
  {
    state: "Kentucky",
    abbr: "KY",
    cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Georgetown", "Richmond", "Florence", "Elizabethtown", "Nicholasville"],
  },
  {
    state: "Louisiana",
    abbr: "LA",
    cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria", "Houma"],
  },
  {
    state: "Maine",
    abbr: "ME",
    cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford", "Sanford", "Brunswick", "Augusta"],
  },
  {
    state: "Maryland",
    abbr: "MD",
    cities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Annapolis", "Hagerstown", "Salisbury", "College Park", "Silver Spring", "Germantown", "Columbia"],
  },
  {
    state: "Massachusetts",
    abbr: "MA",
    cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy", "Lynn", "New Bedford", "Fall River", "Newton", "Somerville", "Lawrence", "Framingham"],
  },
  {
    state: "Michigan",
    abbr: "MI",
    cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Dearborn", "Livonia", "Troy", "Westland", "Farmington Hills", "Flint", "Kalamazoo", "Wyoming", "Southfield", "Rochester Hills"],
  },
  {
    state: "Minnesota",
    abbr: "MN",
    cities: ["Minneapolis", "Saint Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park", "Plymouth", "Woodbury", "Maple Grove", "St. Cloud", "Eagan", "Eden Prairie"],
  },
  {
    state: "Mississippi",
    abbr: "MS",
    cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian", "Tupelo", "Olive Branch", "Greenville"],
  },
  {
    state: "Missouri",
    abbr: "MO",
    cities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles", "St. Peters", "Blue Springs", "Joplin"],
  },
  {
    state: "Montana",
    abbr: "MT",
    cities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell"],
  },
  {
    state: "Nebraska",
    abbr: "NE",
    cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Norfolk", "Hastings"],
  },
  {
    state: "Nevada",
    abbr: "NV",
    cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City", "Fernley", "Elko"],
  },
  {
    state: "New Hampshire",
    abbr: "NH",
    cities: ["Manchester", "Nashua", "Concord", "Dover", "Rochester", "Keene", "Portsmouth", "Laconia"],
  },
  {
    state: "New Jersey",
    abbr: "NJ",
    cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Lakewood", "Edison", "Woodbridge", "Toms River", "Hamilton", "Trenton", "Clifton", "Camden", "Brick", "Cherry Hill", "Passaic", "Union City", "Bayonne", "East Orange", "Vineland", "New Brunswick", "Hoboken", "Atlantic City"],
  },
  {
    state: "New Mexico",
    abbr: "NM",
    cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Clovis", "Hobbs"],
  },
  {
    state: "New York",
    abbr: "NY",
    cities: ["New York City", "Buffalo", "Yonkers", "Rochester", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Hempstead", "Troy", "Niagara Falls", "Binghamton", "Freeport", "Valley Stream"],
  },
  {
    state: "North Carolina",
    abbr: "NC",
    cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Concord", "Asheville", "Greenville", "Gastonia", "Jacksonville", "Chapel Hill"],
  },
  {
    state: "North Dakota",
    abbr: "ND",
    cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson"],
  },
  {
    state: "Ohio",
    abbr: "OH",
    cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Mentor", "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield", "Kettering", "Elyria"],
  },
  {
    state: "Oklahoma",
    abbr: "OK",
    cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton", "Moore", "Midwest City", "Enid", "Stillwater"],
  },
  {
    state: "Oregon",
    abbr: "OR",
    cities: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Bend", "Beaverton", "Medford", "Springfield", "Corvallis", "Albany", "Tigard"],
  },
  {
    state: "Pennsylvania",
    abbr: "PA",
    cities: ["Philadelphia", "Pittsburgh", "Allentown", "Reading", "Scranton", "Erie", "Bethlehem", "Lancaster", "Harrisburg", "Altoona", "York", "State College", "Wilkes-Barre", "Chester"],
  },
  {
    state: "Rhode Island",
    abbr: "RI",
    cities: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence", "Woonsocket", "Newport", "Central Falls"],
  },
  {
    state: "South Carolina",
    abbr: "SC",
    cities: ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville", "Summerville", "Sumter", "Goose Creek", "Hilton Head Island", "Florence", "Spartanburg", "Myrtle Beach"],
  },
  {
    state: "South Dakota",
    abbr: "SD",
    cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Yankton", "Pierre"],
  },
  {
    state: "Tennessee",
    abbr: "TN",
    cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Bartlett", "Hendersonville", "Kingsport"],
  },
  {
    state: "Texas",
    abbr: "TX",
    cities: [
      "Houston",
      "San Antonio",
      "Dallas",
      "Austin",
      "Fort Worth",
      "El Paso",
      "Arlington",
      "Corpus Christi",
      "Plano",
      "Laredo",
      "Lubbock",
      "Garland",
      "Irving",
      "Amarillo",
      "Grand Prairie",
      "Brownsville",
      "McKinney",
      "Frisco",
      "Pasadena",
      "Mesquite",
      "Killeen",
      "McAllen",
      "Waco",
      "Denton",
      "Midland",
      "Carrollton",
      "Round Rock",
      "Abilene",
      "Odessa",
      "Beaumont",
      "Pearland",
      "Richardson",
      "The Woodlands",
      "College Station",
      "Lewisville",
      "Tyler",
      "Allen",
      "League City",
      "Sugar Land",
      "Edinburg",
      "Wichita Falls",
      "San Angelo",
    ],
  },
  {
    state: "Utah",
    abbr: "UT",
    cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy", "Ogden", "St. George", "Layton", "South Jordan", "Lehi", "Millcreek"],
  },
  {
    state: "Vermont",
    abbr: "VT",
    cities: ["Burlington", "South Burlington", "Rutland", "Essex", "Colchester", "Bennington", "Brattleboro", "Milton", "Hartford", "Montpelier"],
  },
  {
    state: "Virginia",
    abbr: "VA",
    cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk", "Lynchburg", "Harrisonburg", "Leesburg", "Charlottesville", "Blacksburg"],
  },
  {
    state: "Washington",
    abbr: "WA",
    cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Spokane Valley", "Federal Way", "Yakima", "Kirkland", "Bellingham", "Kennewick", "Auburn", "Pasco", "Marysville", "Lakewood", "Redmond", "Olympia"],
  },
  {
    state: "West Virginia",
    abbr: "WV",
    cities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Weirton", "Fairmont", "Martinsburg", "Beckley"],
  },
  {
    state: "Wisconsin",
    abbr: "WI",
    cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse"],
  },
  {
    state: "Wyoming",
    abbr: "WY",
    cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan", "Green River", "Evanston", "Riverton", "Jackson"],
  },
  {
    state: "District of Columbia",
    abbr: "DC",
    cities: ["Washington"],
  },
] as const;
