import {useEffect,useState} from 'react';
type Snapshot={settings:{enabled:boolean};schedule:string;heartbeat:{received_at:string}|null;providers:{openai:boolean;claude:boolean;ratesCurrent:boolean};jobs:{job_key:string;kind:string;site_id:string|null;status:string;details:Record<string,unknown>;created_at:string}[];triage:{report_id:string;priority:string;findings:string[];draft:string;updated_at:string}[]};
export function AutomationPanel({queue=false}:{queue?:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function refresh(){const r=await fetch('/api/admin/automation',{credentials:'same-origin'});if(!r.ok)throw new Error('Administrator access is required, or automation status is temporarily unavailable.');setData(await r.json());}
 useEffect(()=>{let active=true;async function poll(){try{const r=await fetch('/api/admin/automation',{credentials:'same-origin'});if(!r.ok)throw new Error('Could not load automation status.');const d=await r.json();if(active){setData(d);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Status unavailable.');}}void poll();const timer=setInterval(()=>{if(document.visibilityState==='visible')void poll();},30000);return()=>{active=false;clearInterval(timer);};},[]);
 async function act(action:string){setBusy(true);setError('');try{const r=await fetch('/api/admin/automation',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed.');setNotice(d.notice);await refresh();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
 const stale=!data?.heartbeat||Date.now()-Date.parse(data.heartbeat.received_at)>15*60*1000;
 return <section className="my-8 rounded-xl border border-line bg-surface p-5"><h2 className="text-2xl font-semibold">Automatic workspace operations</h2><p className="mt-2 text-sm text-muted">{data?.schedule||'Loading schedule…'}</p>{error&&<p role="alert" className="mt-3 text-hot">{error}</p>}{notice&&<p role="status" className="mt-3">{notice}</p>}{data&&<><p className="mt-3">{data.settings.enabled?'Enabled':'Paused'} · Worker signal: {stale?'missing or stale — check the scheduler':'healthy'} · AI readiness: {data.providers.openai&&data.providers.claude&&data.providers.ratesCurrent?'ready':'provider setup or pricing refresh needed'}</p><p className="mt-2 text-xs text-muted">The existing five-minute site worker drives this schedule while these pages are closed. Shared spending limits apply. Customer messages, protected settings and production changes require human approval. Follow-up text below is a draft. Pausing affects new jobs; in-progress work may finish.</p><div className="my-4 flex gap-4"><button disabled={busy} onClick={()=>void act(data.settings.enabled?'pause':'resume')} className="rounded border border-line px-4 py-2">{data.settings.enabled?'Pause automation':'Resume automation'}</button><button disabled={busy||!data.settings.enabled} onClick={()=>void act('run')} className="rounded bg-volt px-4 py-2 text-black">Run due work now</button></div><p className="text-sm">Checks and triage have no AI token cost. Specialist analysis uses the existing shared budget. External service charges remain separate.</p>{queue?<div className="mt-5 space-y-4">{data.triage.length===0?<p>No reports currently need automatic triage.</p>:data.triage.map(t=><article key={t.report_id} className="border-t border-line pt-4"><h3 className="font-semibold">{t.report_id} · {t.priority.replaceAll('_',' ')}</h3>{t.findings.map(f=><p key={f} className="text-sm text-muted">{f}</p>)}<details className="mt-2"><summary>Prepared follow-up draft</summary><p className="mt-2 whitespace-pre-wrap text-sm">{t.draft}</p></details></article>)}</div>:<div className="mt-4 space-y-2">{data.jobs.slice(0,12).map(j=><details key={j.job_key} className="border-t border-line pt-2"><summary>{j.kind} · {j.site_id||'Both sites / comparison queue'} · {j.status} · {new Date(j.created_at).toLocaleString()}</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(j.details,null,2)}</pre></details>)}</div>}</>}</section>;
}
