import {useEffect,useState} from 'react';
import {capabilities} from '@/lib/control-capabilities';
type Status={budget:{enabled:boolean;daily_limit:number;monthly_limit:number};usage:{daily:number;monthly:number;held:number};providers:{openai:boolean;claude:boolean;ratesCurrent:boolean};runs:{id:string;site_id:string;bot_id:string;status:string;artifact:string|null;review:string|null}[]};
export function HostedBots({site}:{site:string}) {
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[id,setId]=useState('');
 const [bot,setBot]=useState<string>(capabilities[0].id),[objective,setObjective]=useState('');
 async function refresh(){const r=await fetch('/api/admin/bot-runs',{credentials:'same-origin'});if(!r.ok)throw new Error('Sign in to view hosted execution.');setData(await r.json());}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));setId(crypto.randomUUID());},[]);
 const ready=data?.budget.enabled&&data.providers.openai&&data.providers.claude&&data.providers.ratesCurrent;
 async function run(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try {const r=await fetch('/api/admin/bot-runs',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,siteId:site,botId:bot,objective})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Run could not start');setId(crypto.randomUUID());await refresh();}catch(e){setError(e instanceof Error?e.message:'Run failed');}finally{setBusy(false);}}
 const money=(v:number)=>'$'+(v/1e6).toFixed(4);
 return <section className="mt-8 rounded-xl border border-line p-6"><h2 className="text-2xl font-semibold">Hosted specialist runs</h2><p className="mt-2 text-muted">All registered specialists can produce analysis or proposed changes, followed by independent Claude review. External website changes, publishing, phone and marketing actions require their own connected executors. This service does not execute those actions.</p>
 {error&&<p role="alert" className="mt-3">{error}</p>}
 {data&&<><p className="mt-3">Shared across both sites: {money(data.usage.daily)} / $2 today; {money(data.usage.monthly)} / $40 this month. Held: {money(data.usage.held)}. Each run reserves $0.10.</p><p className="mt-2">OpenAI: {data.providers.openai?'configured':'missing key'} · Claude: {data.providers.claude?'configured':'missing key'} · Shared budget: {data.budget.enabled?'enabled':'awaiting cutover'} · Pricing: {data.providers.ratesCurrent?'current':'refresh required'}</p></>}
 <form onSubmit={run} className="mt-4 space-y-3"><fieldset disabled={busy||!ready}><label className="block">Specialist<select className="ml-3 border border-line bg-surface p-2" value={bot} onChange={e=>{setBot(e.target.value);setId(crypto.randomUUID());}}>{capabilities.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="mt-3 block">Objective and supporting facts<textarea className="mt-2 block w-full rounded border border-line bg-surface p-3" minLength={8} maxLength={4000} required value={objective} onChange={e=>{setObjective(e.target.value);setId(crypto.randomUUID());}}/></label><button className="mt-3 rounded bg-volt px-4 py-3 text-black" disabled={busy||!ready}>{busy?'Running and reviewing…':'Run specialist and independent review'}</button></fieldset></form>
 <button className="mt-3 underline" onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh results</button>
 {data?.runs.filter(r=>r.site_id===site).map(r=><article key={r.id} className="mt-5 border-t border-line pt-4"><h3>{r.bot_id} — {r.status}</h3><p className="mt-2 whitespace-pre-wrap">{r.artifact}</p><p className="mt-2 whitespace-pre-wrap text-muted">{r.review}</p></article>)}</section>;
}
