/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/growth': typeof GrowthRoute
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/growth': typeof GrowthRoute
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/contact': typeof ContactRoute
  '/growth': typeof GrowthRoute
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/automation' | '/contact' | '/growth' | '/process' | '/websites' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automation' | '/contact' | '/growth' | '/process' | '/websites' | '/work'
  id: '__root__' | '/' | '/automation' | '/contact' | '/growth' | '/process' | '/websites' | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  ContactRoute: typeof ContactRoute
  GrowthRoute: typeof GrowthRoute
  ProcessRoute: typeof ProcessRoute
  WebsitesRoute: typeof WebsitesRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  ContactRoute: ContactRoute,
  GrowthRoute: GrowthRoute,
  ProcessRoute: ProcessRoute,
  WebsitesRoute: WebsitesRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
