/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as WorkRouteImport } from './routes/work'
import { Route as CryptoIndexRouteImport } from './routes/crypto.index'
import { Route as CryptoBitcoinRouteImport } from './routes/crypto.bitcoin'
import { Route as CryptoBusinessRouteImport } from './routes/crypto.business'
import { Route as CryptoContractorsRouteImport } from './routes/crypto.contractors'
import { Route as CryptoEducationRouteImport } from './routes/crypto.education'
import { Route as CryptoIndividualsRouteImport } from './routes/crypto.individuals'
import { Route as CryptoVsBlockchainRouteImport } from './routes/crypto.vs-blockchain'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesContractorsRouteImport } from './routes/industries.contractors'
import { Route as IndustriesHospitalityRouteImport } from './routes/industries.hospitality'
import { Route as IndustriesLandscapingRouteImport } from './routes/industries.landscaping'
import { Route as IndustriesProfessionalsRouteImport } from './routes/industries.professionals'
import { Route as IndustriesServiceCompaniesRouteImport } from './routes/industries.service-companies'
import { Route as IndustriesStoresRouteImport } from './routes/industries.stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoBitcoinRoute = CryptoBitcoinRouteImport.update({
  id: '/bitcoin',
  path: '/bitcoin',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoBusinessRoute = CryptoBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoContractorsRoute = CryptoContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoEducationRoute = CryptoEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoIndividualsRoute = CryptoIndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoVsBlockchainRoute = CryptoVsBlockchainRouteImport.update({
  id: '/vs-blockchain',
  path: '/vs-blockchain',
  getParentRoute: () => CryptoRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesContractorsRoute = IndustriesContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesHospitalityRoute = IndustriesHospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesLandscapingRoute = IndustriesLandscapingRouteImport.update({
  id: '/landscaping',
  path: '/landscaping',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesProfessionalsRoute = IndustriesProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesServiceCompaniesRoute =
  IndustriesServiceCompaniesRouteImport.update({
    id: '/service-companies',
    path: '/service-companies',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesStoresRoute = IndustriesStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/growth': typeof GrowthRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/crypto/bitcoin': typeof CryptoBitcoinRoute
  '/crypto/business': typeof CryptoBusinessRoute
  '/crypto/contractors': typeof CryptoContractorsRoute
  '/crypto/education': typeof CryptoEducationRoute
  '/crypto/individuals': typeof CryptoIndividualsRoute
  '/crypto/vs-blockchain': typeof CryptoVsBlockchainRoute
  '/industries/contractors': typeof IndustriesContractorsRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/landscaping': typeof IndustriesLandscapingRoute
  '/industries/professionals': typeof IndustriesProfessionalsRoute
  '/industries/service-companies': typeof IndustriesServiceCompaniesRoute
  '/industries/stores': typeof IndustriesStoresRoute
  '/crypto/': typeof CryptoIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/growth': typeof GrowthRoute
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/crypto/bitcoin': typeof CryptoBitcoinRoute
  '/crypto/business': typeof CryptoBusinessRoute
  '/crypto/contractors': typeof CryptoContractorsRoute
  '/crypto/education': typeof CryptoEducationRoute
  '/crypto/individuals': typeof CryptoIndividualsRoute
  '/crypto/vs-blockchain': typeof CryptoVsBlockchainRoute
  '/industries/contractors': typeof IndustriesContractorsRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/landscaping': typeof IndustriesLandscapingRoute
  '/industries/professionals': typeof IndustriesProfessionalsRoute
  '/industries/service-companies': typeof IndustriesServiceCompaniesRoute
  '/industries/stores': typeof IndustriesStoresRoute
  '/crypto': typeof CryptoIndexRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/growth': typeof GrowthRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/process': typeof ProcessRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/crypto/bitcoin': typeof CryptoBitcoinRoute
  '/crypto/business': typeof CryptoBusinessRoute
  '/crypto/contractors': typeof CryptoContractorsRoute
  '/crypto/education': typeof CryptoEducationRoute
  '/crypto/individuals': typeof CryptoIndividualsRoute
  '/crypto/vs-blockchain': typeof CryptoVsBlockchainRoute
  '/industries/contractors': typeof IndustriesContractorsRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/landscaping': typeof IndustriesLandscapingRoute
  '/industries/professionals': typeof IndustriesProfessionalsRoute
  '/industries/service-companies': typeof IndustriesServiceCompaniesRoute
  '/industries/stores': typeof IndustriesStoresRoute
  '/crypto/': typeof CryptoIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/claims'
    | '/contact'
    | '/crypto'
    | '/growth'
    | '/industries'
    | '/process'
    | '/websites'
    | '/work'
    | '/crypto/bitcoin'
    | '/crypto/business'
    | '/crypto/contractors'
    | '/crypto/education'
    | '/crypto/individuals'
    | '/crypto/vs-blockchain'
    | '/industries/contractors'
    | '/industries/hospitality'
    | '/industries/landscaping'
    | '/industries/professionals'
    | '/industries/service-companies'
    | '/industries/stores'
    | '/crypto/'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/claims'
    | '/contact'
    | '/growth'
    | '/process'
    | '/websites'
    | '/work'
    | '/crypto/bitcoin'
    | '/crypto/business'
    | '/crypto/contractors'
    | '/crypto/education'
    | '/crypto/individuals'
    | '/crypto/vs-blockchain'
    | '/industries/contractors'
    | '/industries/hospitality'
    | '/industries/landscaping'
    | '/industries/professionals'
    | '/industries/service-companies'
    | '/industries/stores'
    | '/crypto'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/claims'
    | '/contact'
    | '/crypto'
    | '/growth'
    | '/industries'
    | '/process'
    | '/websites'
    | '/work'
    | '/crypto/bitcoin'
    | '/crypto/business'
    | '/crypto/contractors'
    | '/crypto/education'
    | '/crypto/individuals'
    | '/crypto/vs-blockchain'
    | '/industries/contractors'
    | '/industries/hospitality'
    | '/industries/landscaping'
    | '/industries/professionals'
    | '/industries/service-companies'
    | '/industries/stores'
    | '/crypto/'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  ClaimsRoute: typeof ClaimsRoute
  ContactRoute: typeof ContactRoute
  CryptoRoute: typeof CryptoRouteWithChildren
  GrowthRoute: typeof GrowthRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  WebsitesRoute: typeof WebsitesRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/bitcoin': {
      id: '/crypto/bitcoin'
      path: '/bitcoin'
      fullPath: '/crypto/bitcoin'
      preLoaderRoute: typeof CryptoBitcoinRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/business': {
      id: '/crypto/business'
      path: '/business'
      fullPath: '/crypto/business'
      preLoaderRoute: typeof CryptoBusinessRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/contractors': {
      id: '/crypto/contractors'
      path: '/contractors'
      fullPath: '/crypto/contractors'
      preLoaderRoute: typeof CryptoContractorsRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/education': {
      id: '/crypto/education'
      path: '/education'
      fullPath: '/crypto/education'
      preLoaderRoute: typeof CryptoEducationRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/individuals': {
      id: '/crypto/individuals'
      path: '/individuals'
      fullPath: '/crypto/individuals'
      preLoaderRoute: typeof CryptoIndividualsRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/vs-blockchain': {
      id: '/crypto/vs-blockchain'
      path: '/vs-blockchain'
      fullPath: '/crypto/vs-blockchain'
      preLoaderRoute: typeof CryptoVsBlockchainRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/contractors': {
      id: '/industries/contractors'
      path: '/contractors'
      fullPath: '/industries/contractors'
      preLoaderRoute: typeof IndustriesContractorsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/hospitality': {
      id: '/industries/hospitality'
      path: '/hospitality'
      fullPath: '/industries/hospitality'
      preLoaderRoute: typeof IndustriesHospitalityRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/landscaping': {
      id: '/industries/landscaping'
      path: '/landscaping'
      fullPath: '/industries/landscaping'
      preLoaderRoute: typeof IndustriesLandscapingRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/professionals': {
      id: '/industries/professionals'
      path: '/professionals'
      fullPath: '/industries/professionals'
      preLoaderRoute: typeof IndustriesProfessionalsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/service-companies': {
      id: '/industries/service-companies'
      path: '/service-companies'
      fullPath: '/industries/service-companies'
      preLoaderRoute: typeof IndustriesServiceCompaniesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/stores': {
      id: '/industries/stores'
      path: '/stores'
      fullPath: '/industries/stores'
      preLoaderRoute: typeof IndustriesStoresRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface CryptoRouteChildren {
  CryptoBitcoinRoute: typeof CryptoBitcoinRoute
  CryptoBusinessRoute: typeof CryptoBusinessRoute
  CryptoContractorsRoute: typeof CryptoContractorsRoute
  CryptoEducationRoute: typeof CryptoEducationRoute
  CryptoIndividualsRoute: typeof CryptoIndividualsRoute
  CryptoVsBlockchainRoute: typeof CryptoVsBlockchainRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
}

const CryptoRouteChildren: CryptoRouteChildren = {
  CryptoBitcoinRoute: CryptoBitcoinRoute,
  CryptoBusinessRoute: CryptoBusinessRoute,
  CryptoContractorsRoute: CryptoContractorsRoute,
  CryptoEducationRoute: CryptoEducationRoute,
  CryptoIndividualsRoute: CryptoIndividualsRoute,
  CryptoVsBlockchainRoute: CryptoVsBlockchainRoute,
  CryptoIndexRoute: CryptoIndexRoute,
}

const CryptoRouteWithChildren =
  CryptoRoute._addFileChildren(CryptoRouteChildren)

interface IndustriesRouteChildren {
  IndustriesContractorsRoute: typeof IndustriesContractorsRoute
  IndustriesHospitalityRoute: typeof IndustriesHospitalityRoute
  IndustriesLandscapingRoute: typeof IndustriesLandscapingRoute
  IndustriesProfessionalsRoute: typeof IndustriesProfessionalsRoute
  IndustriesServiceCompaniesRoute: typeof IndustriesServiceCompaniesRoute
  IndustriesStoresRoute: typeof IndustriesStoresRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesContractorsRoute: IndustriesContractorsRoute,
  IndustriesHospitalityRoute: IndustriesHospitalityRoute,
  IndustriesLandscapingRoute: IndustriesLandscapingRoute,
  IndustriesProfessionalsRoute: IndustriesProfessionalsRoute,
  IndustriesServiceCompaniesRoute: IndustriesServiceCompaniesRoute,
  IndustriesStoresRoute: IndustriesStoresRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  ClaimsRoute: ClaimsRoute,
  ContactRoute: ContactRoute,
  CryptoRoute: CryptoRouteWithChildren,
  GrowthRoute: GrowthRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  ProcessRoute: ProcessRoute,
  WebsitesRoute: WebsitesRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
